/**
 * Generated by tsnapi — public API snapshot of `nostics/reporters/dev`
 */
// #region Functions
export declare function createDevReporter(): DiagnosticReporter;
// #endregion

// #region Variables
export declare const devReporter: DiagnosticReporter;
// #endregion