/**
 * Generated by tsnapi — public API snapshot of `nostics/reporters/node`
 */
// #region Interfaces
export interface FileReporterOptions {
  logFile?: string;
}
// #endregion

// #region Functions
export declare function createFileReporter(_?: FileReporterOptions): DiagnosticReporter;
// #endregion