/**
 * Generated by tsnapi — public API snapshot of `logs-sdk/reporters/node` */
// Interfaces
export interface FileReporterOptions {
  logFile?: string;
}

// Functions
export declare function createFileReporter(_?: FileReporterOptions): DiagnosticReporter;