catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground
  - demo-lib
  - docs
  - packages/*
  - examples/*
catalog:
  esbuild: ^0.28.0
catalogs:
  cli:
    '@antfu/eslint-config': ^8.2.0
    '@antfu/ni': ^30.0.0
    '@posva/prompts': ^2.4.4
    '@vitejs/devtools': ^0.1.13
    bumpp: ^11.0.1
    conventional-changelog: ^7.2.0
    conventional-changelog-angular: ^8.3.1
    eslint: ^10.2.0
    lint-staged: ^16.4.0
    publint: ^0.3.18
    semver: ^7.7.4
    simple-git-hooks: ^2.13.1
    tsdown: ^0.21.8
    typescript: ^6.0.2
    vite: ^8.0.8
    vite-plugin-inspect: ^12.0.0-beta.1
  deps:
    magic-string: ^0.30.21
    oxc-parser: ^0.126.0
    unplugin: ^3.0.0
  inlined:
    '@antfu/utils': ^9.3.0
  playground:
    '@vitejs/plugin-vue': ^6.0.0
    vue: ^3.5.13
  testing:
    tsnapi: ^0.3.0
    vitest: ^4.1.4
  types:
    '@types/node': ^25.6.0
    '@types/semver': ^7.7.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
