/**
 * Generated by tsnapi — public API snapshot of `nostics/unplugin/dev`
 */
// #region Interfaces
export interface NosticsCollectorOptions {
  logFile?: string;
  debug?: boolean;
}
// #endregion

// #region Variables
export declare const nosticsCollector: UnpluginInstance<NosticsCollectorOptions | undefined>;
// #endregion