/**
 * Generated by tsnapi — public API snapshot of `nostics/unplugin/strip`
 */
// #region Types
export type NosticsStripOptions = TransformOptions;
// #endregion

// #region Variables
export declare const nosticsStrip: UnpluginInstance<NosticsStripOptions | undefined>;
// #endregion

// #region Default Export
declare const _default: UnpluginInstance<NosticsStripOptions | undefined>;
export default _default
// #endregion