/**
 * Generated by tsnapi — public API snapshot of `nostics/dev`
 */
// #region Interfaces
export interface NosticsServerOptions {
  logFile?: string;
  debug?: boolean;
}
// #endregion

// #region Variables
export declare const nosticsServer: UnpluginInstance<NosticsServerOptions | undefined>;
// #endregion