/**
 * Generated by tsnapi — public API snapshot of `logs-sdk` */
// Interfaces
export interface CreateLoggerOptions<D extends readonly any[]> {
  diagnostics: [...D];
  formatter?: Formatter;
  reporters?: Reporter | Reporter[];
  captureStack?: boolean;
}
export interface DefineDiagnosticsOptions<C extends Record<string, DiagnosticDefinition>> {
  docsBase?: string | ((_: string) => string | undefined);
  codes: C;
}
export interface Diagnostic {
  code: string;
  level: DiagnosticLevel;
  message: string;
  why?: string;
  fix?: string;
  hint?: string;
  docs?: string;
  sources?: SourceLocation[];
  cause?: unknown;
  context?: Record<string, unknown>;
  stack?: string;
}
export interface DiagnosticActions extends Diagnostic {
  throw: () => never;
  warn: () => void;
  error: () => void;
  log: () => void;
  format: () => string;
}
export interface DiagnosticDefinition {
  message: MessageTemplate;
  fix?: MessageTemplate;
  why?: MessageTemplate;
  hint?: MessageTemplate;
  level?: DiagnosticLevel;
}
export interface DiagnosticsMethods<C extends Record<string, DiagnosticDefinition>> {
  codes: () => (keyof C & string)[];
  has: (_: string) => code is Extract<keyof C, string>;
  get: <K extends keyof C>(_: K) => C[K];
  extend: <U extends Record<string, DiagnosticDefinition>>(_: U) => DiagnosticsResult<C & U>;
}
export interface LoggerMethods {
  throw: (_: Diagnostic) => never;
  warn: (_: Diagnostic) => void;
  error: (_: Diagnostic) => void;
  log: (_: Diagnostic) => void;
  format: (_: Diagnostic) => string;
}
export interface SourceLocation {
  file?: string;
  line?: number;
  column?: number;
}

// Types
export type CodeFactory<T> = IsEmptyObject<ExtractParams<T>> extends true ? (overrides?: Overrides) => Diagnostic : (params: Simplify<ExtractParams<T>>, overrides?: Overrides) => Diagnostic;
export type DiagnosticLevel = "error" | "warn" | "suggestion" | "deprecation";
export type DiagnosticsResult<C extends Record<string, DiagnosticDefinition>> = { [K in keyof C]: CodeFactory<C[K]> } & DiagnosticsMethods<C>;
export type Formatter = (_: Diagnostic) => string;
export type Logger<D extends readonly any[]> = MergeFactories<D> & LoggerMethods;
export type MergeFactories<D extends readonly any[]> = D extends readonly [infer First, ...infer Rest] ? ActionFactories<First> & MergeFactories<Rest> : {};
export type Overrides = Partial<Pick<Diagnostic, "level" | "sources" | "cause" | "context">>;
export type Reporter = (_: Diagnostic, _: string) => void;

// Classes
export declare class CodedError extends Error {
  readonly diagnostic: Diagnostic;
  constructor(_: Diagnostic);
}

// Functions
export declare function createFetchReporter(_: string): Reporter;
export declare function createLogger<const D extends readonly any[]>(_: CreateLoggerOptions<D>): Logger<D>;
export declare function defineDiagnostics<C extends Record<string, DiagnosticDefinition>>(_: DefineDiagnosticsOptions<C>): DiagnosticsResult<C>;
export declare function formatTag(_: Diagnostic): string;
export declare function renderFrame(_: Diagnostic): string;

// Variables
export declare const consoleReporter: Reporter;
export declare const plainFormatter: Formatter;