/**
 * Generated by tsnapi — public API snapshot of `nostics`
 */
// #region Interfaces
export interface DefineDiagnosticsOptions<Codes extends Record<string, DiagnosticDefinition>, Reporters extends readonly AnyDiagnosticReporter[]> {
  docsBase?: string | ((_: keyof Codes) => string | undefined);
  codes: Codes;
  reporters?: Reporters;
}
export interface DiagnosticCallParams {
  cause?: unknown;
  sources?: string[];
}
export interface DiagnosticDefinition<P = any> {
  why: ValueOrFn<string, P>;
  fix?: ValueOrFn<string, P>;
  docs?: string | false;
}
export interface DiagnosticHandle<Params, ReporterOpts> {
  (..._: ActionArgs<Params, ReporterOpts>): Diagnostic;
}
export interface DiagnosticInit extends DiagnosticCallParams {
  why: string;
  fix?: string;
  docs?: string;
}
// #endregion

// #region Types
export type _ValueOrFn<T, P = any> = T | ((_: P) => T);
export type DiagnosticReporter<ReporterOpts extends object = {}> = (_: Diagnostic, _: ReporterOpts) => void;
// #endregion

// #region Classes
export declare class Diagnostic extends Error {
  name: string;
  docs?: string;
  fix?: string;
  sources?: string[];
  get why(): string;
  constructor(_: DiagnosticInit, _?: Function);
  toJSON(): object;
  devOnly?: () => void;
}
// #endregion

// #region Functions
export declare function defineDiagnostics<const Codes extends Record<string, DiagnosticDefinition>, const Reporters extends readonly AnyDiagnosticReporter[]>(_: DefineDiagnosticsOptions<Codes, Reporters>): Diagnostics<Codes, Reporters>;
export declare function formatDiagnostic(_: Diagnostic): string;
export declare function reporterError(_: Diagnostic): void;
export declare function reporterLog(_: Diagnostic, {
  method
}?: {
  method?: "log" | "error" | "warn";
}): void;
// #endregion