/**
 * Generated by tsnapi — public API snapshot of `nostics/lib`
 */
<<<<<<< HEAD:__snapshots__/tsnapi/unplugin.snapshot.d.ts
// #region Interfaces
export interface NosticsServerOptions {
  logFile?: string;
  debug?: boolean;
  excludeStackFrames?: readonly RegExp[];
}
// #endregion

=======
>>>>>>> 241e465 (refactor!: split nostics/unplugin into nostics/lib and nostics/dev):__snapshots__/tsnapi/lib.snapshot.d.ts
// #region Types
export type NosticsPluginOptions = TransformOptions;
// #endregion

// #region Variables
export declare const nostics: UnpluginInstance<NosticsPluginOptions | undefined>;
// #endregion

// #region Default Export
declare const _default: UnpluginInstance<NosticsPluginOptions | undefined>;
export default _default
// #endregion