/**
 * Generated by tsnapi — public API snapshot of `nostics/node` */
// Interfaces
export interface FileReporterOptions {
  logFile?: string;
}

// Functions
export declare function createFileReporter(_?: FileReporterOptions): Reporter;