/**
 * Generated by tsnapi — public API snapshot of `nostics/unplugin` */
// Interfaces
export interface LogsSdkServerOptions {
  logFile?: string;
}

// Types
export type LogsSdkPluginOptions = TransformOptions;

// Variables
export declare const logsSDK: UnpluginInstance<LogsSdkPluginOptions | undefined>;
export declare const logsSDKServer: UnpluginInstance<LogsSdkServerOptions | undefined>;

// Default Export
declare const _default: UnpluginInstance<LogsSdkPluginOptions | undefined>;
export default _default