/**
 * Generated by tsnapi — public API snapshot of `logs-sdk/unplugin`
 */
// #region Interfaces
export interface LogsSdkServerOptions {
  logFile?: string;
  debug?: boolean;
}
// #endregion

// #region Types
export type LogsSdkPluginOptions = TransformOptions;
// #endregion

// #region Variables
export declare const logsSDK: UnpluginInstance<LogsSdkPluginOptions | undefined>;
export declare const logsSDKServer: UnpluginInstance<LogsSdkServerOptions | undefined>;
// #endregion

// #region Default Export
declare const _default: UnpluginInstance<LogsSdkPluginOptions | undefined>;
export default _default
// #endregion