/**
 * Generated by tsnapi — public API snapshot of `nostics/unplugin`
 */
// #region Interfaces
export interface NosticsServerOptions {
  logFile?: string;
  debug?: boolean;
  excludeStackFrames?: readonly RegExp[];
}
// #endregion

// #region Types
export type NosticsPluginOptions = TransformOptions;
// #endregion

// #region Variables
export declare const nostics: UnpluginInstance<NosticsPluginOptions | undefined>;
export declare const nosticsServer: UnpluginInstance<NosticsServerOptions | undefined>;
// #endregion

// #region Default Export
declare const _default: UnpluginInstance<NosticsPluginOptions | undefined>;
export default _default
// #endregion