/**
 * Generated by tsnapi — public API snapshot of `logs-sdk/formatters/ansi` */
// Interfaces
export interface Colors {
  red: (_: string) => string;
  yellow: (_: string) => string;
  cyan: (_: string) => string;
  gray: (_: string) => string;
  bold: (_: string) => string;
  dim: (_: string) => string;
}

// Functions
export declare function ansiFormatter(_: Colors): (_: Diagnostic) => string;