/**
 * Generated by tsnapi — public API snapshot of `nostics/formatters/ansi` */
// Interfaces
export interface Colors {
  red: (s: string) => string;
  yellow: (s: string) => string;
  cyan: (s: string) => string;
  gray: (s: string) => string;
  bold: (s: string) => string;
  dim: (s: string) => string;
}

// Functions
export declare function ansiFormatter(_: Colors): Formatter;