/**
 * Generated by tsnapi — public API snapshot of `nostics/formatters/ansi`
 */
// #region Interfaces
export interface Colors {
  red: (_: string) => string;
  yellow: (_: string) => string;
  cyan: (_: string) => string;
  gray: (_: string) => string;
  bold: (_: string) => string;
  dim: (_: string) => string;
}
// #endregion

// #region Functions
export declare function ansiFormatter(_: Colors): (_: Diagnostic) => string;
// #endregion