name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: pnpm exec vitest run --coverage
      # docs and playgrounds should also work
      - run: pnpm -C demo-lib run build
      - run: pnpm -C playground run build
      - run: pnpm -C docs run build
